config/routes.rb
Rails.application.routes.draw do
  get 'profiles/index'
  get 'users/index'
  root 'products#index'
  devise_for :users
  resources :products, only: [:new, :create, :index, :show]
  resources :reviews, only: [:index, :new, :create, :show]
  resources :profiles, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :reviews, dependent: :destroy
    has_one :profile, through: :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  enum usertypes: {individual:0 , company: 1, bulkuser: 2}
  # creating an enum to usertype and used that in view
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one :profile
  has_many :products
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    end
end


# i don't why i have written this doing in a blind way

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  
  def index
        @users = User.all
        @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create 
    @product = Product.new(product_params)
    if @product.save
      # incorporating job in controller that means enqueing a job
      #it was using the active job only
      SimpleJob.perform_now('world');
      redirect_to products_path
    else
      flash[:alert] = 'Unable to register Product'
      render :new
    end
  end


  def show
    @product = Product.find(params[:id]);
    respond_to do |format|
      format.html
      format.json {render json: @product}
    end
  end


  def update
    
  end

  private
  def product_params
    params.require(:product).permit(:productId, :productName, :productDescription);
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all 
  end

  def new
    @profile = Profile.new
    @users = User.all
  end

  def create
    @profile = Profile.new(profile_params)
    @user = User.all
    if @profile.save
      # here we have pass the instance variable not the class variable
      ProfileJob.perform_now(@profile.created_at,@profile.updated_at)
      redirect_to profiles_index_path
    else
      flash[:alert] = "unable to create a profile"
      redirect_to profiles_index_path
    end
  end


  private

  def profile_params 
   params.require(:profile).permit(:user_id, :usertype)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    @products = Product.all
  end

  def create 
    @review = Review.new(review_params)
    @products = Product.all 
    if @review.save
      flash[:notice] = 'review successfully submitted'
      redirect_to reviews_path
    else
      flash[:alert] = 'unable to submit review'
      render :new
    end
  end


  def show
    @review = Review.find(params[:id]);
    respond_to do |format|
      format.html
      format.json {render json: @review}
    end
  end


  private
  def review_params
    params.require(:review).permit(:comment, :product_id);
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoductReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_record_actions.html.erb
<%= link_to 'Back To Products',products_path, class: 'btn btn-primary', style: "color: black" %>

 

app/views/products/index.html.erb
<%= link_to 'All Products',products_path, class: 'btn btn-primary float-right ml-2', style: "color: black" %>
<%= link_to 'New Product', new_product_path, class: 'btn btn-primary float-right ml-2', style: "color: black" %>
<% if user_signed_in? %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-primary float-right', style: "color: black" %>
<% end %>
<br>
<br>
<table class = "table table-striped",  style = "width: 50%">
    <thead class = " thead thead-dark">
        <tr>
            <th>productId</th>
            <th>productName</th>
            <th>productDescription</th>
            <th>Product Comment</th>
            <th>Updated By</th>
        </tr>
    </thead>
    <tbody>
            <% @products.each do |product| %>
                <tr class = "tr">
                    <td> <%=link_to product.productId, product_path(product) %> </td>
                    <td> <%= product.productName %> </td>
                    <td> <%= product.productDescription %> </td>
                    <td>
                        <% if product.reviews.any? %>
                          <% product.reviews.each do |review| %>
                            <p><%= review.comment %></p>
                          <% end %>
                        <% else %>
                          No reviews yet
                    <td> <%= product.user_id %> </td>
                        <% end %>
                    </td>
                </tr>
            <% end %>
    </tbody>
</table>

app/views/products/new.html.erb
<%= form_with model: @product, id: 'productForm', local: true do |form| %> 
  <div>
    <%= form.label :productId, "Product ID" %>
    <%= form.text_field :productId %> 
    <br>
  </div>
  <div>
    <%= form.label :productName, "Product Name" %>
    <%= form.text_field :productName %> 
    <br>
  </div>
  <div>
    <%= form.label :productDescription, "Product Description" %>
    <%= form.text_field :productDescription %>
  </div>
  <%= button_tag "Register Product" %>
<% end %>

app/views/products/show.html.erb
<p><strong>Product ID:</strong> <%= @product.id %></p>
<p><strong>Product Name:</strong> <%= @product.productName %></p>
<p><strong>Product Description:</strong> <%= @product.productDescription %></p>
<%= render partial: 'record_actions'%>

app/views/profiles/index.html.erb
<table class = "table table-striped",  style = "width: 50%">
    <thead class = " thead thead-dark">
        <tr>
            <th>Username</th>
            <th>userType</th>
        </tr>
    </thead>
    <tbody>
            <% @profiles.each do |profile| %>
                <tr class = "tr">
                    <!-- have to use the safe navigation operator to check the user presence when profile was created -->
                    <td><%= profile.user&.username || 'No User' %></td>
                    <td><%=profile.usertype %></td>
                </tr>
            <% end %>
    </tbody>
</table>

app/views/profiles/new.html.erb
<h1>creating a profile for user</h1>
<%= form_with model: @profile, local: true do |form| %>
<div class = "py-3">
    <%= form.label :UserName %>
    <%= form.select :user_id, options_from_collection_for_select(@users, 'id', 'username'), { prompt: "Choose a user", style: "display: block;" } %>
</div>

</div>
<div class = "py-3">
    <%= form.label :usertype %>
    <%= form.select :usertype, Profile.usertypes.keys.map { |usertype| [usertype.titleize, usertype] }, prompt: "Select User Type" %>
</div>

<div>
    <%= form.submit "create Profile" %>
</div>
<% end %>

app/views/reviews/index.html.erb
<table class = "table table-striped",  style = "width: 50%">
    <thead class = " thead thead-dark">
        <tr>
            <th>productName</th>
            <th>comment</th>
        </tr>
    </thead>
    <tbody>
            <% @reviews.each do |review| %>
                <tr class = "tr">
                    <td><%= link_to review.product.productName, review_path(review) %></td>
                    <td><%=review.comment %></td>
                </tr>
            <% end %>
    </tbody>
</table>

app/views/reviews/new.html.erb
<h1>Please give a review for our products</h1>
<%= form_with model: @review, local: true do |form| %>
<div class="py-3">
    <%= form.select :product_id, options_from_collection_for_select(@products, 'productId', 'productName'), { prompt: "Choose a product" }, style: "display: block;" %>
  </div>
  
<div class = "py-3">
    <%= form.label :comment, "comment" %>
    <%= form.text_field :comment,{ promt: "Leave a Comment Here" } %>
</div>

<div>
    <%= form.submit "Save Review" %>
</div>
<% end %>

app/views/reviews/show.html.erb
<p><strong>ProductName:</strong> <%= @review.product.productName %></p>
<p><strong>comment:</strong> <%= @review.comment %></p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>